language: python

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - pypy
      - python3.5

python: 3.6

env:
  matrix:
    - TOXENV=py27-dj18
    - TOXENV=py27-dj110
    - TOXENV=py34-dj18
    - TOXENV=py34-dj110
    - TOXENV=py35-dj18
    - TOXENV=py35-dj110
    - TOXENV=pypy-dj18
    - TOXENV=pypy-dj110
    - TOXENV=py27-dj111
    - TOXENV=py34-dj20
    - TOXENV=py35-dj20
    - TOXENV=py36-dj20
    - TOXENV=flake8

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
