language: python

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - pypy
      - python3.6
      - python3.7
      - python3.8

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  matrix:
    - TOXENV=py36-dj22
    - TOXENV=py37-dj22
    - TOXENV=py38-dj22

    - TOXENV=flake8

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install flake8 tox 'coverage<5' coveralls

jobs:
  include:
    - name: flake8
      python: "3.6"
      script: flake8 djclick

script:
  - tox -e $TOXENV
  - coverage report
  - coverage html
  - coveralls
