language: python

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - pypy
      - python3.6

python:
  - "3.6"

env:
  - TOXENV=dj22
  - TOXENV=dj30

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install flake8 tox 'coverage<5' coveralls

script:
  - tox -e $TOXENV
  - coverage report
  - coverage html
  - coveralls

jobs:
  include:
    - script: tox -e flake8
