language: python

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - pypy
      - python3.6

python:
  - "3.6"
  - "3.7"

env:
  matrix:
    - TOXENV=dj111
    - TOXENV=dj20
    - TOXENV=dj21

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install flake8 tox 'coverage<5' coveralls

jobs:
  include:
    - name: flake8
      python: "3.6"
      script: flake8 djclick

script:
  - tox -e $TOXENV
  - coverage report
  - coverage html
  - coveralls
