language: python

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - pypy
      - python3.6

python: 3.7

env:
  matrix:
    - TOXENV=py36-dj111
    - TOXENV=py37-dj111
    - TOXENV=pypy-dj111
    - TOXENV=py36-dj20
    - TOXENV=py37-dj20
    - TOXENV=py36-dj21
    - TOXENV=py37-dj21
    - TOXENV=flake8

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
